# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing google servive cloud server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 35.232.203.142
        username: gleb
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          git pull origin master
          
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         python manage.py test
  
  
# #   deploy:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - uses: actions/checkout@v2
# #       - name: Set up Python 3.8
# #         uses: actions/setup-python@v2
# #         with:
# #           python-version: 3.8
# #       # Setup key
# #       - run: set -eu
# #       - run: mkdir "$HOME/.ssh"
# #       - run: echo "${{ secret.KEY}}" > "$HOME/.ssh/key"
# #       - run: chmod 600 "$HOME/.ssh/key"
# #       # Build
# #       - run: npm ci
# #       - run: npm build
# #       # Deploy
# #       - run: git pull
  
  
  
  
#   deploy2:
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#     - uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.DEPLOY_SERVER_HOST }}
#         username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
#         key: ${{ secrets.DEPLOY_SERVER_KEY }}
#         port: ${{ secrets.PORT }}
#         source: "github/belhardtask1"
#         target: "belhardtask1"
